[package]
name = "ynab-export"
version = "0.0.6"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"
description = "ynab-export is a tool to help export a YNAB budget to a database"
repository = "https://git.tozt.net/ynab-export"
license = "MIT"

[dependencies]
directories = "6"
tokio = { version = "1", features = ["full"] }
ynab-api = "4"
